title: Sourav Saha
logo: assets/My_image (1).jpg
description: Hi, I'm Sourav. I'm working as a machine learning engineer at Reve Systems. I completed my undergraduate studies at CSE, SUST with distinction. I'm fascinated by the capabilities of large 
             language models and want to explore their potential for solving real-life problems. Reach out to me at [gmail](souravsaha0152@gmail.com)
show_downloads: False
theme: jekyll-theme-minimal
